import type { Asset, AssistantEvidenceResult, AssistantToolName, DataTrust, Incident, IncidentDetail, OperationsApi, OperationsSummary, TransitionInput } from "./types";

const delay = <T,>(value: T) => new Promise<T>((resolve) => setTimeout(() => resolve(value), 180));
const assets: Asset[] = [
  { id: "primary-crusher-01", name: "Primary Crusher 01", area: "Crushing", type: "Crusher", health: "attention", availability: 91.4, lastObservedAt: "2026-08-08T17:48:00Z" },
  { id: "conveyor-17", name: "Transfer Conveyor 17", area: "Crushing", type: "Conveyor", health: "watch", availability: 97.8, lastObservedAt: "2026-08-08T17:49:00Z" },
  { id: "wash-plant-02", name: "Wash Plant 02", area: "Processing", type: "Wash plant", health: "good", availability: 99.1, lastObservedAt: "2026-08-08T17:48:00Z" },
  { id: "stacker-04", name: "Radial Stacker 04", area: "Loadout", type: "Stacker", health: "good", availability: 98.6, lastObservedAt: "2026-08-08T17:47:00Z" },
];
let incidents: IncidentDetail[] = [
  { id: "inc-2048", title: "Crusher drive vibration above operating envelope", state: "investigating", severity: "critical", assetIds: ["primary-crusher-01"], openedAt: "2026-08-08T13:14:00Z", updatedAt: "2026-08-08T17:31:00Z", summary: "Repeated high axial vibration during loaded cycles. Operating envelope exceeded on three confirmed observations.", confidence: 94, evidenceCount: 3, evidence: [{ id: "ev-1", observedAt: "2026-08-08T17:28:00Z", source: "Condition monitor", title: "Axial vibration: 12.8 mm/s", detail: "Above configured review threshold of 10.0 mm/s during loaded operating state.", quality: "verified" }, { id: "ev-2", observedAt: "2026-08-08T16:42:00Z", source: "Condition monitor", title: "Axial vibration: 12.1 mm/s", detail: "Corroborating observation; source clock synchronized.", quality: "verified" }, { id: "ev-3", observedAt: "2026-08-08T15:09:00Z", source: "Operator record", title: "Intermittent audible rumble", detail: "Operator observation attached to current run window.", quality: "review" }], timeline: [{ id: "tl-1", occurredAt: "2026-08-08T13:14:00Z", kind: "created", actor: "Detection service", text: "Incident opened from correlated condition findings." }, { id: "tl-2", occurredAt: "2026-08-08T15:21:00Z", kind: "transition", actor: "J. Rivera", text: "State changed to acknowledged", reason: "Confirmed trend and assigned field inspection." }, { id: "tl-3", occurredAt: "2026-08-08T17:31:00Z", kind: "transition", actor: "M. Chen", text: "State changed to investigating", reason: "Maintenance inspection requested for next safe access window." }] },
  { id: "inc-2044", title: "Conveyor 17 throughput variance", state: "acknowledged", severity: "high", assetIds: ["conveyor-17"], openedAt: "2026-08-08T10:06:00Z", updatedAt: "2026-08-08T16:10:00Z", summary: "Measured flow intermittently diverges from expected line balance.", confidence: 87, evidenceCount: 2, evidence: [], timeline: [] },
  { id: "inc-2039", title: "Wash plant moisture feed delayed", state: "open", severity: "medium", assetIds: ["wash-plant-02"], openedAt: "2026-08-08T08:32:00Z", updatedAt: "2026-08-08T14:02:00Z", summary: "Source freshness exceeded the operating data window.", confidence: 76, evidenceCount: 1, evidence: [], timeline: [] },
];
const trust: DataTrust = { score: 96, observedSources: 14, delayedSources: 1, schemaWarnings: 0, lastEvaluatedAt: "2026-08-08T17:49:00Z", feeds: [{ name: "Condition monitoring", freshness: "42 sec", state: "healthy", coverage: 99 }, { name: "Production historian", freshness: "1 min", state: "healthy", coverage: 98 }, { name: "Lab moisture results", freshness: "31 min", state: "delayed", coverage: 93 }, { name: "Operator rounds", freshness: "6 min", state: "healthy", coverage: 97 }] };

export const demoApi: OperationsApi = {
  getSummary: () => delay({ productionRate: 842, productionDelta: 4.8, availability: 96.7, activeIncidents: incidents.filter((i) => !["resolved", "dismissed"].includes(i.state)).length, dataTrust: trust.score, lastObservedAt: "2026-08-08T17:49:00Z" }),
  listIncidents: () => delay(incidents.map(({ evidence, timeline, ...incident }) => incident)),
  getIncident: async (id) => { const incident = incidents.find((item) => item.id === id); if (!incident) throw new Error("Incident not found"); return delay(incident); },
  transitionIncident: async (id, input: TransitionInput) => { if (!input.reason.trim()) throw new Error("A reason is required for lifecycle changes."); const index = incidents.findIndex((item) => item.id === id); if (index < 0) throw new Error("Incident not found"); const prior = incidents[index]; const at = new Date().toISOString(); incidents[index] = { ...prior, state: input.state, updatedAt: at, timeline: [...prior.timeline, { id: `tl-${at}`, occurredAt: at, kind: "transition", actor: "Demo operator", text: `State changed to ${input.state}`, reason: input.reason }] }; return delay(incidents[index]); },
  listAssets: () => delay(assets),
  getDataTrust: () => delay(trust),
  runAssistantTool: async (toolName: AssistantToolName, arguments_: Record<string, unknown>): Promise<AssistantEvidenceResult> => {
    const incidentId = typeof arguments_.incident_id === "string" ? arguments_.incident_id : undefined;
    const assetId = typeof arguments_.asset_id === "string" ? arguments_.asset_id : undefined;
    const selected = incidentId ? incidents.filter((item) => item.id === incidentId) : assetId ? incidents.filter((item) => item.assetIds.includes(assetId)) : incidents;
    const records: Array<Record<string, unknown>> = (toolName === "get_incident_evidence" ? selected.flatMap((item) => item.evidence) : toolName === "list_recent_findings" ? [{ trust_score: trust.score, delayed_sources: trust.delayedSources, schema_warnings: trust.schemaWarnings }] : selected.map(({ evidence, timeline, ...item }) => item)).map((record) => ({ ...record }));
    return delay({ mode: "deterministic_evidence_tool", toolName, siteId: "sonoran-west", records, citations: records.map((record, index) => ({ id: String(record.id ?? record.incident_id ?? `local-${index + 1}`), type: toolName, source: "Local demo adapter", observed_at: String(record.observedAt ?? record.updatedAt ?? trust.lastEvaluatedAt), asset_id: assetId })), uncertaintyNotes: ["Local demo evidence only; it is not a live platform query."], truncated: false });
  },
};
